import Vue from 'vue'
import { Tabs, Tab, Checkbox, Dialog, ActionSheet, Cell, Button, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Grid, GridItem, Icon } from 'vant'
Vue.use(Button)
Vue.use(Tabbar)
Vue.use(NavBar)
Vue.use(TabbarItem)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Cell)
Vue.use(ActionSheet)
Vue.use(Dialog)
Vue.use(Checkbox)
Vue.use(Tab)
Vue.use(Tabs)
